name: almotamayez
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  dio: ^5.3.2
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  pretty_dio_logger: ^1.3.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

# ! To change icon
# flutter clean
# flutter pub get
# flutter pub run flutter_launcher_icons
# ! To Rename
# flutter pub global activate rename
# flutter pub global run rename --appname "AppName"
# flutter pub global run rename --bundleId com.comp.appname


flutter:

  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/
    - assets/svgs/

  fonts:
    # - family: Poppins
    #   fonts:
    #     - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
    #       weight: 100
    #     - asset: assets/fonts/Poppins/Poppins-Thin.ttf
    #       weight: 200
    #     - asset: assets/fonts/Poppins/Poppins-Light.ttf
    #       weight: 300
    #     - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/Poppins/Poppins-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/Poppins/Poppins-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/Poppins/Poppins-Black.ttf
    #       weight: 800
    #     - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
    #       weight: 900
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
          weight: 100
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 200
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
          weight: 400
      